# Generated by Django 5.2.2 on 2025-06-14 20:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(error_messages={'blank': 'Email boş bırakılamaz', 'invalid': 'Geçersiz email', 'unique': 'Bu email zaten kullanılıyor'}, max_length=254, unique=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, null=True, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir')),
                ('country', models.CharField(blank=True, default='Türkiye', max_length=50, null=True, verbose_name='Ülke')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('CU', 'Müşteri'), ('VE', 'Satıcı'), ('AD', 'Yönetici')], default='CU', max_length=2, verbose_name='Kullanıcı Rolü')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='Profil Fotoğrafı')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(blank=True, default=False)),
                ('phone_verified', models.BooleanField(blank=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'user',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['role'], name='user_role_3744fd_idx')],
            },
        ),
    ]
