# Generated by Django 5.2.2 on 2025-06-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='user_role_3744fd_idx',
            old_name='accounts_cu_role_666d59_idx',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
