# Generated by Django 5.2.2 on 2025-06-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
