# Generated by Django 5.2.2 on 2025-06-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sold_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
    ]
