# Generated by Django 5.2.2 on 2025-08-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_favoriteproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cached_path",
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
